version: '2.1'
services:
  web:
    image: filegator-apache
    build:
      context: .
    ports:
      - "80:80"
    expose:
      - "80"
    volumes:
      - "filegator_repository:/var/www/repository:rw"

volumes:
  filegator_repository: